#!/usr/bin/env python3
"""Scaffold the required design-system-output folder structure for a run."""

from __future__ import annotations

import argparse
from pathlib import Path


# Files the pipeline scripts generate themselves. Scaffolding them as empty
# placeholders would mask a stage that silently failed to run, so they are
# listed here only for the directory tree and are never written.
GENERATED_BY_PIPELINE = [
    "tokens/tokens.json",
    "tokens/tokens.css",
    "tokens/tailwind.theme.js",
    "tokens/tailwind.theme.css",
    "tokens/tokens.source.json",
    "tokens/preview.html",
    "components/component-contracts.json",
    "evidence/crawl-manifest.json",
    "evidence/measured-raw.json",
    "evidence/extraction-confidence.json",
    "evidence/contrast-findings.json",
    "evidence/component-observations.json",
    "evidence/dark-mode.json",
    "evidence/fidelity-report.json",
    "evidence/raw-vs-canonical-diff.md",
    "reports/fidelity-check.md",
]

# Narrative artifacts the synthesis prompts write. These get placeholders.
REQUIRED_FILES = [
    "reports/executive-summary.md",
    "reports/source-audit.md",
    "reports/brand-dna.md",
    "reports/accessibility-audit.md",
    "reports/preserve-normalize-improve-exclude.md",
    "components/component-library-spec.md",
    "patterns/page-template-patterns.md",
    "evidence/page-weights.json",
]

DIRECTORIES = ["reports", "tokens", "components", "patterns", "evidence", "evidence/pages", "evidence/screenshots"]


PLACEHOLDERS = {
    ".md": "<!-- Generated by design-system-extractor. Fill after pipeline stages complete. -->\n",
    ".json": "{}\n",
    ".css": "/* Generated by design-system-extractor */\n:root {\n}\n",
    ".js": "// Generated by design-system-extractor\nmodule.exports = {\n  theme: { extend: {} }\n};\n",
}


def write_placeholder(path: Path, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(PLACEHOLDERS.get(path.suffix, ""), encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "output_dir",
        nargs="?",
        default="design-system-output",
        help="Root output directory to create (default: design-system-output)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite placeholder files if they already exist",
    )
    args = parser.parse_args()

    root = Path(args.output_dir)
    for directory in DIRECTORIES:
        (root / directory).mkdir(parents=True, exist_ok=True)

    created = 0
    skipped = 0
    for rel in REQUIRED_FILES:
        changed = write_placeholder(root / rel, force=args.force)
        if changed:
            created += 1
        else:
            skipped += 1

    print(f"Scaffolded {created} placeholder file(s) and {len(DIRECTORIES)} directories under {root}")
    if skipped:
        print(f"Skipped {skipped} existing files (use --force to overwrite placeholders)")
    print(f"{len(GENERATED_BY_PIPELINE)} further artifacts are written by the pipeline scripts, not scaffolded:")
    print("  discover_urls.py -> capture_site.mjs -> aggregate_tokens.py -> emit_tokens.py -> fidelity_check.mjs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
