#!/usr/bin/env python3
"""Validate the design-system-output package before handoff.

Checks that every required artifact exists, that the measurement evidence is
actually present (not placeholder), and that the claims in the reports are
backed by the measured data. Run this last.

Exit codes: 0 pass (possibly with warnings), 1 fail.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

# Artifacts written by the pipeline scripts. Missing any of these means a stage
# did not run, so the package is inference rather than measurement.
MEASUREMENT_PATHS = [
    "evidence/crawl-manifest.json",
    "evidence/measured-raw.json",
    "evidence/extraction-confidence.json",
    "evidence/contrast-findings.json",
    "evidence/component-observations.json",
    "evidence/raw-vs-canonical-diff.md",
    "tokens/tokens.source.json",
    "tokens/tokens.json",
    "tokens/tokens.css",
    "tokens/tailwind.theme.js",
    "tokens/tailwind.theme.css",
    "tokens/preview.html",
    "components/component-contracts.json",
]

# Narrative artifacts written by the synthesis prompts.
NARRATIVE_PATHS = [
    "reports/executive-summary.md",
    "reports/source-audit.md",
    "reports/brand-dna.md",
    "reports/accessibility-audit.md",
    "reports/preserve-normalize-improve-exclude.md",
    "components/component-library-spec.md",
    "patterns/page-template-patterns.md",
]

RECOMMENDED_PATHS = [
    "evidence/fidelity-report.json",
    "reports/fidelity-check.md",
    "evidence/dark-mode.json",
    "evidence/page-weights.json",
]

PLACEHOLDER_MARKER = "Generated by design-system-extractor. Fill after pipeline"


def parse_json(path: Path) -> tuple[Any | None, str | None]:
    try:
        return json.loads(path.read_text(encoding="utf-8")), None
    except Exception as exc:  # noqa: BLE001
        return None, str(exc)


def require_keys(obj: dict[str, Any], keys: list[str], label: str, errors: list[str]) -> None:
    missing = [k for k in keys if k not in obj]
    if missing:
        errors.append(f"{label}: missing keys {missing}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output_dir", nargs="?", default="design-system-output")
    parser.add_argument(
        "--allow-unmeasured",
        action="store_true",
        help="downgrade missing measurement artifacts to warnings (not for handoff)",
    )
    args = parser.parse_args()

    root = Path(args.output_dir)
    errors: list[str] = []
    warnings: list[str] = []

    for rel in MEASUREMENT_PATHS:
        if not (root / rel).exists():
            message = (
                f"Missing measurement artifact: {rel}. The pipeline stage that writes it did not run, "
                "so any tokens in this package are inferred rather than measured."
            )
            (warnings if args.allow_unmeasured else errors).append(message)
    for rel in NARRATIVE_PATHS:
        if not (root / rel).exists():
            errors.append(f"Missing required report: {rel}")
    for rel in RECOMMENDED_PATHS:
        if not (root / rel).exists():
            warnings.append(f"Missing recommended artifact: {rel}")

    if errors:
        for message in errors:
            print(f"ERROR: {message}")
        print(f"Validation failed ({len(errors)} error(s))")
        return 1

    # --- placeholders left unfilled -------------------------------------
    for rel in NARRATIVE_PATHS:
        text = (root / rel).read_text(encoding="utf-8")
        if PLACEHOLDER_MARKER in text or len(text.strip()) < 120:
            errors.append(f"{rel}: still a placeholder / near-empty ({len(text.strip())} chars)")

    # --- tokens.json must be DTCG and carry provenance -------------------
    tokens_path = root / "tokens/tokens.json"
    data, err = parse_json(tokens_path)
    if err:
        errors.append(f"{tokens_path}: invalid JSON ({err})")
    elif not isinstance(data, dict):
        errors.append(f"{tokens_path}: expected top-level object")
    else:
        for group in ("color", "dimension", "typography"):
            if group not in data:
                errors.append(f"{tokens_path}: missing required token group '{group}'")
        semantic = (data.get("color") or {}).get("semantic") or {}
        real_semantic = {k: v for k, v in semantic.items() if not k.startswith("$")}
        if not real_semantic:
            errors.append(f"{tokens_path}: color.semantic is empty; nothing can consume a primitive-only token set")
        typed = [k for k, v in real_semantic.items() if isinstance(v, dict) and "$value" in v]
        if len(typed) != len(real_semantic):
            errors.append(f"{tokens_path}: color.semantic entries must use DTCG $value")
        without_provenance = [
            k for k, v in real_semantic.items()
            if not (v.get("$extensions", {}).get("psdsm", {}) or {}).get("evidence_pages")
        ]
        if without_provenance:
            warnings.append(
                f"{tokens_path}: {len(without_provenance)} semantic colour(s) carry no evidence_pages provenance"
            )

    # --- confidence report must use the computed model -------------------
    confidence_path = root / "evidence/extraction-confidence.json"
    data, err = parse_json(confidence_path)
    if err:
        errors.append(f"{confidence_path}: invalid JSON ({err})")
    elif isinstance(data, dict):
        require_keys(data, ["threshold", "model", "pages_measured", "fidelity_mode"], str(confidence_path), errors)
        if not (data.get("model") or {}).get("formula"):
            errors.append(f"{confidence_path}: model.formula missing; confidence must be computed, not asserted")
        if data.get("pages_measured", 0) < 1:
            errors.append(f"{confidence_path}: pages_measured is 0")
        low = data.get("low_confidence_tokens") or []
        if low:
            warnings.append(f"{len(low)} token(s) below the confidence threshold: {low[:6]}")
    else:
        errors.append(f"{confidence_path}: expected top-level object")

    # --- crawl manifest --------------------------------------------------
    manifest_path = root / "evidence/crawl-manifest.json"
    data, err = parse_json(manifest_path)
    if err:
        errors.append(f"{manifest_path}: invalid JSON ({err})")
    elif isinstance(data, dict):
        require_keys(data, ["source_url", "pages"], str(manifest_path), errors)
        pages = data.get("pages") or []
        if not pages:
            errors.append(f"{manifest_path}: no pages captured")
        shot_count = sum(
            1 for p in pages if any("screenshot" in key for key in (p.get("captures") or {}))
        )
        if shot_count < len(pages):
            warnings.append(f"{manifest_path}: {len(pages) - shot_count} page(s) captured without screenshots")
        if data.get("errors"):
            warnings.append(f"{manifest_path}: {len(data['errors'])} capture error(s) recorded")
    else:
        errors.append(f"{manifest_path}: expected top-level object")

    # --- component contracts must separate measured from recommended ------
    contracts_path = root / "components/component-contracts.json"
    data, err = parse_json(contracts_path)
    if err:
        errors.append(f"{contracts_path}: invalid JSON ({err})")
    elif isinstance(data, dict):
        components = data.get("components") or []
        if not components:
            errors.append(f"{contracts_path}: no components")
        for component in components:
            states = component.get("states") or {}
            untagged = [name for name, body in states.items() if not (body or {}).get("source")]
            if untagged:
                errors.append(
                    f"{contracts_path}: {component.get('name')} state(s) {untagged} have no `source` tag; "
                    "measured and recommended states must be distinguishable"
                )
            if not component.get("accessibility", {}).get("has_visible_focus_indicator", True):
                warnings.append(f"{component.get('name')}: no visible focus indicator measured on the source")
        gaps = [c.get("name") for c in components if c.get("unmeasured_states")]
        if gaps:
            warnings.append(f"component(s) with unmeasured states (design recommendations, not extractions): {gaps}")
    else:
        errors.append(f"{contracts_path}: expected top-level object")

    # --- contrast findings ------------------------------------------------
    contrast_path = root / "evidence/contrast-findings.json"
    data, _ = parse_json(contrast_path)
    if isinstance(data, dict):
        failing = (data.get("summary") or {}).get("failing_pairs", 0)
        if failing:
            unresolved = [
                p for p in data.get("pairs", [])
                if not p.get("wcag_aa") and not p.get("accessible_alternative")
            ]
            warnings.append(f"{failing} colour pair(s) fail WCAG AA")
            if unresolved:
                errors.append(
                    f"{contrast_path}: {len(unresolved)} failing pair(s) have no accessible alternative"
                )

    # --- fidelity gate ----------------------------------------------------
    fidelity_path = root / "evidence/fidelity-report.json"
    if fidelity_path.exists():
        data, err = parse_json(fidelity_path)
        if isinstance(data, dict):
            summary = data.get("summary") or {}
            grade = summary.get("palette_fidelity")
            delta = summary.get("mean_palette_delta_e")
            if grade == "low":
                errors.append(
                    f"Fidelity check failed: mean palette ΔE {delta} against the source pixels. "
                    "The token set does not reproduce what the site renders — re-check colour role "
                    "assignment and capture coverage before handoff."
                )
            elif grade == "moderate":
                warnings.append(f"Fidelity is moderate (mean palette ΔE {delta}); spot-check tokens/preview.html")
            coverage = summary.get("mean_pixel_share_covered")
            if isinstance(coverage, (int, float)) and coverage < 0.75:
                warnings.append(
                    f"Only {coverage:.0%} of dominant source pixels map to a token; "
                    "imagery or an unextracted surface colour may be missing"
                )

    # --- diff must be present and honest ----------------------------------
    diff_path = root / "evidence/raw-vs-canonical-diff.md"
    if diff_path.exists():
        text = diff_path.read_text(encoding="utf-8")
        if "Fidelity mode:" not in text:
            warnings.append(f"{diff_path}: does not state the fidelity mode used")

    # --- PNIE + non-derivative language -----------------------------------
    pnie = (root / "reports/preserve-normalize-improve-exclude.md").read_text(encoding="utf-8")
    for term in ("Preserve", "Normalize", "Improve", "Exclude"):
        if term not in pnie:
            warnings.append(f"PNIE report does not mention '{term}'")

    summary_text = (root / "reports/executive-summary.md").read_text(encoding="utf-8").lower()
    markers = ["not a clone", "brand-faithful", "normalize", "must not be copied"]
    if not any(marker in summary_text for marker in markers):
        warnings.append("Executive summary may be missing explicit non-derivative guardrail language")

    for message in errors:
        print(f"ERROR: {message}")
    for message in warnings:
        print(f"WARN: {message}")

    if errors:
        print(f"Validation failed ({len(errors)} error(s), {len(warnings)} warning(s))")
        return 1
    print(f"Validation passed with {len(warnings)} warning(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
