#!/usr/bin/env python3
"""Scaffold the required design-system-output folder structure for a run."""

from __future__ import annotations

import argparse
from pathlib import Path


REQUIRED_FILES = [
    "reports/executive-summary.md",
    "reports/source-audit.md",
    "reports/brand-dna.md",
    "reports/accessibility-audit.md",
    "reports/preserve-normalize-improve-exclude.md",
    "tokens/tokens.json",
    "tokens/tokens.css",
    "tokens/tailwind.theme.js",
    "components/component-library-spec.md",
    "components/component-contracts.json",
    "patterns/page-template-patterns.md",
    "evidence/crawl-manifest.json",
    "evidence/page-weights.json",
    "evidence/extraction-confidence.json",
]


PLACEHOLDERS = {
    ".md": "<!-- Generated by public-site-design-system-modernizer. Fill after pipeline stages complete. -->\n",
    ".json": "{}\n",
    ".css": "/* Generated by public-site-design-system-modernizer */\n:root {\n}\n",
    ".js": "// Generated by public-site-design-system-modernizer\nmodule.exports = {\n  theme: { extend: {} }\n};\n",
}


def write_placeholder(path: Path, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(PLACEHOLDERS.get(path.suffix, ""), encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "output_dir",
        nargs="?",
        default="design-system-output",
        help="Root output directory to create (default: design-system-output)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite placeholder files if they already exist",
    )
    args = parser.parse_args()

    root = Path(args.output_dir)
    created = 0
    skipped = 0
    for rel in REQUIRED_FILES:
        changed = write_placeholder(root / rel, force=args.force)
        if changed:
            created += 1
        else:
            skipped += 1

    print(f"Scaffolded {created} files under {root}")
    if skipped:
        print(f"Skipped {skipped} existing files (use --force to overwrite placeholders)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
