#!/usr/bin/env python3
"""emit_tokens.py — turn a validated token spec into files a codebase consumes.

Emits the same semantic layer into every target platform so the meaning of
"primary", "selected", "pending", and "unavailable" stays identical across web,
iOS, and Android while the expression stays native. Colour pairs are annotated
with their measured contrast so the ratio travels with the token instead of
living in a review doc nobody opens.

Usage:
  python3 emit_tokens.py token-spec.json --out tokens/
  python3 emit_tokens.py token-spec.json --out tokens/ --formats css,tailwind4
  python3 emit_tokens.py token-spec.json --out tokens/ --preview

Formats: css, tailwind3, tailwind4, json, swift, android  (default: all)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.color import contrast, parse_color  # noqa: E402
from check_contrast import check_spec  # noqa: E402

ALL_FORMATS = ["css", "tailwind3", "tailwind4", "json", "swift", "android"]


def _banner_lines(spec: dict) -> list[str]:
    return [
        f"Generated by premium-calm/emit_tokens.py from the {spec.get('project', 'project')} token spec.",
        "Semantic layer only — components consume these names, never raw values.",
        "Regenerate rather than editing by hand; hand-edits drift from the contrast checks.",
    ]


def _banner(spec: dict, prefix: str = "", extra: str | None = None) -> str:
    """Banner with `prefix` on every line, so each format's comment syntax holds."""
    lines = _banner_lines(spec) + ([extra] if extra else [])
    return "\n".join(f"{prefix}{line}".rstrip() for line in lines)


def _contrast_notes(spec: dict) -> dict[str, list[str]]:
    """Map each token to the pairs it participates in, with measured ratios."""
    notes: dict[str, list[str]] = {}
    for result in check_spec(spec):
        if result["ratio"] is None:
            continue
        line = f"{result['mode']}: {result['ratio']}:1 vs {result['bg']} (min {result['min']})"
        notes.setdefault(result["fg"], []).append(line)
    return notes


# ---------------------------------------------------------------------- CSS

def emit_css(spec: dict) -> str:
    prefix = spec.get("prefix", "pc")
    modes = spec.get("color", {})
    notes = _contrast_notes(spec)
    light = modes.get("light", {})
    dark = modes.get("dark", {})

    def color_block(palette: dict, indent: str = "  ") -> str:
        lines = []
        for name, value in palette.items():
            note = notes.get(name)
            comment = f"  /* {note[0]} */" if note else ""
            lines.append(f"{indent}--{prefix}-color-{name}: {value};{comment}")
        return "\n".join(lines)

    out = ["/*\n" + _banner(spec, " * ") + "\n */\n", ":root {"]
    out.append("  /* colour — light */")
    out.append(color_block(light))

    if spec.get("type"):
        out.append("\n  /* type */")
        for name, t in spec["type"].items():
            out.append(f"  --{prefix}-type-{name}-size: {t['size']};")
            out.append(f"  --{prefix}-type-{name}-line: {t['line']};")
            if t.get("tracking"):
                out.append(f"  --{prefix}-type-{name}-tracking: {t['tracking']};")
            if t.get("weight"):
                out.append(f"  --{prefix}-type-{name}-weight: {t['weight']};")

    if spec.get("space", {}).get("scale"):
        out.append("\n  /* spacing — larger gaps between concepts than within a component */")
        for step in spec["space"]["scale"]:
            out.append(f"  --{prefix}-space-{step}: {step}px;")

    if spec.get("radius"):
        out.append("\n  /* radius — an inner element never exceeds its parent's radius */")
        for name, value in spec["radius"].items():
            out.append(f"  --{prefix}-radius-{name}: {value}px;")

    if spec.get("motion"):
        out.append("\n  /* motion */")
        for name, m in spec["motion"].items():
            ms = m["ms"] if isinstance(m, dict) else m
            use = f"  /* {m['use']} */" if isinstance(m, dict) and m.get("use") else ""
            out.append(f"  --{prefix}-motion-{name}: {ms}ms;{use}")

    out.append("}")

    if dark:
        out.append("\n/* Dark mode overrides the semantic layer only — never the primitives. */")
        out.append('@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {')
        out.append(color_block(dark, "    "))
        out.append("  }\n}")
        out.append('\n:root[data-theme="dark"] {')
        out.append(color_block(dark))
        out.append("}")

    out.append(
        "\n/* Reduced motion is a mode, not a fallback: spatial and decorative movement\n"
        "   collapses to an immediate state change, and nothing essential is carried\n"
        "   by movement alone. */\n"
        "@media (prefers-reduced-motion: reduce) {\n"
        "  :root {"
    )
    for name in (spec.get("motion") or {}):
        out.append(f"    --{prefix}-motion-{name}: 1ms;")
    out.append("  }\n"
               "  *, *::before, *::after {\n"
               "    animation-duration: 1ms !important;\n"
               "    animation-iteration-count: 1 !important;\n"
               "    transition-duration: 1ms !important;\n"
               "    scroll-behavior: auto !important;\n"
               "  }\n}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- Tailwind

def emit_tailwind3(spec: dict) -> str:
    prefix = spec.get("prefix", "pc")
    light = spec.get("color", {}).get("light", {})
    colors = {name: f"var(--{prefix}-color-{name})" for name in light}
    spacing = {str(s): f"var(--{prefix}-space-{s})" for s in spec.get("space", {}).get("scale", [])}
    radius = {name: f"var(--{prefix}-radius-{name})" for name in spec.get("radius", {})}
    duration = {name: f"var(--{prefix}-motion-{name})" for name in spec.get("motion", {})}
    font_size = {
        name: [f"var(--{prefix}-type-{name}-size)", {"lineHeight": f"var(--{prefix}-type-{name}-line)"}]
        for name in spec.get("type", {})
    }
    theme = {
        "extend": {
            "colors": colors,
            "spacing": spacing,
            "borderRadius": radius,
            "transitionDuration": duration,
            "fontSize": font_size,
        }
    }
    body = json.dumps(theme, indent=2)
    return (
        _banner(spec, "// ") + "\n"
        "// Tailwind v3. Values resolve CSS custom properties, so retheming needs no rebuild.\n"
        "// Requires tokens.css to be loaded.\n\n"
        f"module.exports = {{\n  theme: {body.replace(chr(10), chr(10) + '  ')},\n}};\n"
    )


def emit_tailwind4(spec: dict) -> str:
    prefix = spec.get("prefix", "pc")
    light = spec.get("color", {}).get("light", {})
    out = [
        "/*\n" + _banner(spec, " * ", "Tailwind v4. Import after tokens.css.") + "\n */",
        "",
        '@import "tailwindcss";',
        "",
        "@theme {",
    ]
    for name in light:
        out.append(f"  --color-{name}: var(--{prefix}-color-{name});")
    for step in spec.get("space", {}).get("scale", []):
        out.append(f"  --spacing-{step}: var(--{prefix}-space-{step});")
    for name in spec.get("radius", {}):
        out.append(f"  --radius-{name}: var(--{prefix}-radius-{name});")
    for name in spec.get("type", {}):
        out.append(f"  --text-{name}: var(--{prefix}-type-{name}-size);")
    out.append("}")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------- JSON

def emit_json(spec: dict) -> str:
    """DTCG-shaped token file with contrast recorded on each colour."""
    notes = _contrast_notes(spec)
    doc: dict = {
        "$description": " ".join(_banner_lines(spec)),
        "color": {},
        "dimension": {},
        "duration": {},
    }
    for mode, palette in spec.get("color", {}).items():
        doc["color"][mode] = {
            name: {
                "$type": "color",
                "$value": value,
                **({"$extensions": {"premium-calm.contrast": notes[name]}} if name in notes else {}),
            }
            for name, value in palette.items()
        }
    doc["dimension"]["space"] = {
        str(s): {"$type": "dimension", "$value": f"{s}px"} for s in spec.get("space", {}).get("scale", [])
    }
    doc["dimension"]["radius"] = {
        name: {"$type": "dimension", "$value": f"{v}px"} for name, v in spec.get("radius", {}).items()
    }
    doc["duration"] = {
        name: {
            "$type": "duration",
            "$value": f"{(m['ms'] if isinstance(m, dict) else m)}ms",
            **({"$description": m["use"]} if isinstance(m, dict) and m.get("use") else {}),
        }
        for name, m in spec.get("motion", {}).items()
    }
    doc["typography"] = {
        name: {"$type": "typography", "$value": t} for name, t in spec.get("type", {}).items()
    }
    return json.dumps(doc, indent=2) + "\n"


# -------------------------------------------------------------------- Swift

def _swift_name(name: str) -> str:
    parts = name.split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def emit_swift(spec: dict) -> str:
    light = spec.get("color", {}).get("light", {})
    dark = spec.get("color", {}).get("dark", {})
    out = [
        _banner(spec, "// "),
        "",
        "import SwiftUI",
        "",
        "public enum PCColor {",
        "    private static func dynamic(_ light: UInt32, _ dark: UInt32) -> Color {",
        "        Color(UIColor { traits in",
        "            UIColor(rgb: traits.userInterfaceStyle == .dark ? dark : light)",
        "        })",
        "    }",
        "",
    ]
    for name, value in light.items():
        dark_value = dark.get(name, value)
        out.append(
            f"    public static let {_swift_name(name)} = dynamic("
            f"0x{parse_color(value)[0]:02X}{parse_color(value)[1]:02X}{parse_color(value)[2]:02X}, "
            f"0x{parse_color(dark_value)[0]:02X}{parse_color(dark_value)[1]:02X}{parse_color(dark_value)[2]:02X})"
        )
    out.append("}")
    out.append("")
    out.append("public enum PCSpace {")
    for s in spec.get("space", {}).get("scale", []):
        out.append(f"    public static let s{s}: CGFloat = {s}")
    out.append("}")
    out.append("")
    out.append("public enum PCRadius {")
    for name, v in spec.get("radius", {}).items():
        out.append(f"    public static let {_swift_name(name)}: CGFloat = {v}")
    out.append("}")
    out.append("")
    out.append("public enum PCMotion {")
    out.append("    /// Honour Reduce Motion: spatial transitions collapse to an immediate state change.")
    out.append("    public static var reduceMotion: Bool { UIAccessibility.isReduceMotionEnabled }")
    for name, m in spec.get("motion", {}).items():
        ms = m["ms"] if isinstance(m, dict) else m
        comment = f"  // {m['use']}" if isinstance(m, dict) and m.get("use") else ""
        out.append(f"    public static var {_swift_name(name)}: Double {{ reduceMotion ? 0.001 : {ms / 1000:.3f} }}{comment}")
    out.append("}")
    out.append("")
    target = spec.get("target", {})
    out.append(f"/// Minimum interactive target on Apple platforms: {target.get('apple', 44)}pt on the minor axis.")
    out.append(f"public let pcMinimumTarget: CGFloat = {target.get('apple', 44)}")
    out.append("")
    out.append("private extension UIColor {")
    out.append("    convenience init(rgb: UInt32) {")
    out.append("        self.init(")
    out.append("            red: CGFloat((rgb >> 16) & 0xFF) / 255,")
    out.append("            green: CGFloat((rgb >> 8) & 0xFF) / 255,")
    out.append("            blue: CGFloat(rgb & 0xFF) / 255,")
    out.append("            alpha: 1")
    out.append("        )")
    out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"


# ------------------------------------------------------------------ Android

def _android_name(name: str) -> str:
    return name.replace("-", "_")


def emit_android(spec: dict) -> dict[str, str]:
    light = spec.get("color", {}).get("light", {})
    dark = spec.get("color", {}).get("dark", {})
    target = spec.get("target", {})

    def colors_xml(palette: dict, label: str) -> str:
        lines = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {label} -->", "<resources>"]
        for name, value in palette.items():
            r, g, b, _ = parse_color(value)
            lines.append(f'    <color name="pc_{_android_name(name)}">#{r:02X}{g:02X}{b:02X}</color>')
        lines.append("</resources>")
        return "\n".join(lines) + "\n"

    dimens = ['<?xml version="1.0" encoding="utf-8"?>', "<resources>"]
    for s in spec.get("space", {}).get("scale", []):
        dimens.append(f'    <dimen name="pc_space_{s}">{s}dp</dimen>')
    for name, v in spec.get("radius", {}).items():
        dimens.append(f'    <dimen name="pc_radius_{_android_name(name)}">{v}dp</dimen>')
    dimens.append(
        f'    <!-- Minimum interactive target on Android: {target.get("android", 48)}dp on the minor axis. -->'
    )
    dimens.append(f'    <dimen name="pc_min_target">{target.get("android", 48)}dp</dimen>')
    dimens.append("</resources>")

    integers = ['<?xml version="1.0" encoding="utf-8"?>', "<resources>"]
    for name, m in spec.get("motion", {}).items():
        ms = m["ms"] if isinstance(m, dict) else m
        if isinstance(m, dict) and m.get("use"):
            integers.append(f"    <!-- {m['use']} -->")
        integers.append(f'    <integer name="pc_motion_{_android_name(name)}">{ms}</integer>')
    integers.append("</resources>")

    files = {
        "android/values/colors.xml": colors_xml(light, _banner(spec, "     ").strip() + "\n     Light mode."),
        "android/values/dimens.xml": "\n".join(dimens) + "\n",
        "android/values/integers.xml": "\n".join(integers) + "\n",
    }
    if dark:
        files["android/values-night/colors.xml"] = colors_xml(dark, _banner(spec, "     ").strip() + "\n     Dark mode.")
    return files


# ------------------------------------------------------------------ preview

def emit_preview(spec: dict) -> str:
    """A page built only from the emitted tokens. If it looks like the brand, the spec held."""
    results = check_spec(spec)
    prefix = spec.get("prefix", "pc")
    swatch_rows = []
    for mode, palette in spec.get("color", {}).items():
        cells = "".join(
            f'<div class="sw"><span style="background:{v}"></span><code>{k}</code><small>{v}</small></div>'
            for k, v in palette.items()
        )
        swatch_rows.append(f"<h3>{mode}</h3><div class='grid'>{cells}</div>")

    pair_rows = "".join(
        f"<tr class='{'ok' if r['pass'] else 'bad'}'><td>{r['mode']}</td><td>{r['fg']}</td>"
        f"<td>{r['bg']}</td><td>{r['ratio'] if r['ratio'] is not None else '—'}</td>"
        f"<td>{r['min']}</td><td>{'pass' if r['pass'] else 'FAIL'}</td></tr>"
        for r in results
    )
    type_rows = "".join(
        f'<p style="font-size:{t["size"]};line-height:{t["line"]};letter-spacing:{t.get("tracking","0")};'
        f'font-weight:{t.get("weight","400")};margin:0 0 12px">{name} — {t.get("use","")}</p>'
        for name, t in spec.get("type", {}).items()
    )
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{spec.get('project', 'Tokens')} — premium-calm token preview</title>
<link rel="stylesheet" href="tokens.css">
<style>
  body {{ background: var(--{prefix}-color-canvas); color: var(--{prefix}-color-text-primary);
         font-family: system-ui, sans-serif; margin: 0; padding: 32px; }}
  h2 {{ margin-top: 48px; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 12px; }}
  .sw span {{ display: block; height: 48px; border-radius: 8px;
              border: 1px solid var(--{prefix}-color-border-subtle); }}
  .sw code {{ display: block; font-size: 12px; margin-top: 6px; }}
  .sw small {{ color: var(--{prefix}-color-text-secondary); font-size: 11px; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 14px; }}
  td, th {{ text-align: left; padding: 6px 10px;
            border-bottom: 1px solid var(--{prefix}-color-border-subtle); }}
  tr.bad {{ color: var(--{prefix}-color-danger); font-weight: 600; }}
  .btn {{ background: var(--{prefix}-color-accent); color: var(--{prefix}-color-accent-ink);
          border: 0; border-radius: var(--{prefix}-radius-full); padding: 14px 24px;
          font-size: 16px; font-weight: 600; min-height: 48px; }}
  .btn:focus-visible {{ outline: 3px solid var(--{prefix}-color-focus); outline-offset: 2px; }}
  .btn.secondary {{ background: transparent; color: var(--{prefix}-color-text-primary);
                    border: 1px solid var(--{prefix}-color-border-default); }}
  .card {{ background: var(--{prefix}-color-surface); border-radius: var(--{prefix}-radius-lg);
           padding: var(--{prefix}-space-24); border: 1px solid var(--{prefix}-color-border-subtle);
           max-width: 420px; }}
</style></head>
<body>
  <h1>{spec.get('project', 'Tokens')} — token preview</h1>
  <p style="color:var(--{prefix}-color-text-secondary);max-width:65ch">
    Every element below is built only from the emitted tokens. If this reads as the brand
    and every pair passes, the spec is ready to propose.
  </p>

  <h2>Colour</h2>
  {''.join(swatch_rows)}

  <h2>Contrast</h2>
  <table><thead><tr><th>mode</th><th>foreground</th><th>background</th><th>ratio</th><th>min</th><th></th></tr></thead>
  <tbody>{pair_rows}</tbody></table>

  <h2>Type</h2>
  {type_rows}

  <h2>Components from tokens only</h2>
  <div class="card">
    <p style="margin:0 0 4px;font-weight:600">One primary action per decision region</p>
    <p style="margin:0 0 16px;color:var(--{prefix}-color-text-secondary);font-size:14px">
      The secondary action must not imitate the primary.</p>
    <button class="btn">Confirm and pay</button>
    <button class="btn secondary">Back</button>
  </div>
</body></html>
"""


# ---------------------------------------------------------------------- main

def main() -> int:
    ap = argparse.ArgumentParser(description="Emit premium-calm tokens for every platform.")
    ap.add_argument("spec", help="token spec JSON")
    ap.add_argument("--out", default="tokens", help="output directory (default: tokens)")
    ap.add_argument("--formats", default=",".join(ALL_FORMATS), help=f"comma-separated: {', '.join(ALL_FORMATS)}")
    ap.add_argument("--preview", action="store_true", help="also write preview.html")
    ap.add_argument("--allow-failing", action="store_true",
                    help="emit even when contrast pairs fail (default: refuse)")
    args = ap.parse_args()

    spec = json.loads(Path(args.spec).read_text())
    formats = [f.strip() for f in args.formats.split(",") if f.strip()]
    unknown = [f for f in formats if f not in ALL_FORMATS]
    if unknown:
        ap.error(f"unknown format(s): {', '.join(unknown)}")

    failures = [r for r in check_spec(spec) if not r["pass"]]
    if failures and not args.allow_failing:
        print(f"Refusing to emit: {len(failures)} contrast pair(s) fail.", file=sys.stderr)
        for r in failures:
            detail = r["error"] or f"{r['ratio']}:1 < {r['min']}"
            print(f"  {r['mode']}: {r['fg']} on {r['bg']} — {detail}", file=sys.stderr)
        print("\nFix the tokens and re-run, or pass --allow-failing to emit anyway.", file=sys.stderr)
        return 1

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    written: list[str] = []

    def write(rel: str, content: str) -> None:
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        written.append(rel)

    if "css" in formats:
        write("tokens.css", emit_css(spec))
    if "tailwind3" in formats:
        write("tailwind.theme.js", emit_tailwind3(spec))
    if "tailwind4" in formats:
        write("tailwind.theme.css", emit_tailwind4(spec))
    if "json" in formats:
        write("tokens.json", emit_json(spec))
    if "swift" in formats:
        write("Tokens.swift", emit_swift(spec))
    if "android" in formats:
        for rel, content in emit_android(spec).items():
            write(rel, content)
    if args.preview:
        write("preview.html", emit_preview(spec))

    print(f"Wrote {len(written)} file(s) to {out}/")
    for rel in written:
        print(f"  {rel}")
    if failures:
        print(f"\nEmitted with {len(failures)} failing contrast pair(s) — do not ship without fixing them.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
